from docx import Document
from docx.shared import Inches
document = Document()
#insert  picture
document.add_picture("keen.png",width=Inches(1.8))

#personal information
document.add_heading("PERSONAL INFORMATION")
name = input("Enter name: ")
age = input("Enter age: ")
ocupation = input("Enter ocupation: ")
email = input("Enter email: ")

document.add_paragraph(
    name +' |'+age + ' |' + ocupation +' |' +email
)
#about me
document.add_heading("About  me")


#education background
p = document.add_paragraph()
school = input("Enter your school: ")
start_year = str(input("Enter year started: "))
end_year = input("Enter your end_year:")

p.add_run(school + ' ').bold = True
p.add_run(start_year + '_' + end_year + '\n').italic = True

qualification_gained= input ("Enter qualification acquired in "+ school)
p.add_run(qualification_gained)

while True:
    has_more_education_background = input("Do you have other education background ?yes or no ")
    if has_more_education_background.lower() == "yes":
        p=document.add_paragraph()

        p = document.add_paragraph()
        school = input("Enter your school: ")
        start_year = str(input("Enter year started: "))
        end_year = input("Enter your end_year:")

        p.add_run(school + ' ').bold = True
        p.add_run(start_year + '_' + end_year + '\n').italic = True

        qualification_gained= input ("Enter qualification acquired in "+ school)
        p.add_run(qualification_gained)

    else:
        break

document.add_heading("skills")
p = document.add_paragraph()
institution = input("Enter institution ")
start_year = input("Enter year started:  ")
end_year = input("Enter year ended: ")

p.add_run(institution + ' ').bold = True
p.add_run(start_year+ '_' + end_year + '\n').italic = True

while True:
    has_more_skill = input("do you have more skills ye or no : ")
    if has_more_skill == "yes":

        p = document.add_paragraph()
        institution = input("Enter institution ")
        start_year = input("Enter year started:  ")
        end_year = input("Enter year ended: ")

        p.add_run(institution + ' ').bold = True
        p.add_run(start_year+ '_' + end_year + '\n').italic = True
    else:
        break
#section
section = document.sections[0]
footer = section.footer
p =footer.paragraphs[0]
p.text = "CV Generated by keen mwangale "












document.save("my_cv.docx")